version: "3"
services:
  bitcoind:
    restart: unless-stopped
    image: lightningcn/bitcoin:0.17.1-amd64
    container_name: lightningcn_bitcoind
    environment:
      BITCOIN_NETWORK: "${BITCOIN_NETWORK:-testnet}"
      BITCOIN_DATA: /data
      BITCOIN_EXTRA_ARGS: |
        disablewallet=1
        txindex=1
        server=1
        rpcuser=rpcuser
        rpcpassword=rpcpass
        rpcport=43782
        port=39388
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    expose:
        - "43782"
        - "39388"
        - "28332"
        - "28333"
    volumes:
        - ./bitcoin_data:/data
 
  lnd_bitcoin:
    image: lightningcn/lnd:v0.5.2-beta-amd64
    container_name: lightningcn_lnd_bitcoin
    restart: unless-stopped
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: ${BITCOIN_NETWORK:-testnet}
      LND_DATA: /data
      LND_BITCOIND: /btcdata
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        rpclisten=127.0.0.1:10008
        rpclisten=0.0.0.0:10009
        bitcoin.node=bitcoind
        bitcoind.rpchost=bitcoind:43782
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        externalip=${LIGHTNING_HOST}:9735
        alias=${LIGHTNING_ALIAS}
        noseedbackup=1
        notls=1
        nat=true
    volumes:
        - ./lnd_data:/data
        - ./bitcoin_data:/btcdata
    ports:
        - "9735:9735"
        - "2222:22"
    expose:
      - "8080"
      - "9735"
    depends_on:
        - bitcoind

  rtl:
    restart: unless-stopped
    image: shahanafarooqui/rtl:0.2.6-amd64
    container_name: lightningcn_rtl-wallet
    environment:
      LND_SERVER_URL: http://lnd_bitcoin:8080/v1
      MACAROON_PATH: "/root/.lnd/data/chain/bitcoin/${BITCOIN_NETWORK:-testnet}"
      LND_CONFIG_PATH: /root/.lnd/lnd.conf
      BITCOIND_CONFIG_PATH: /root/.bitcoin/bitcoin.conf
      NODE_AUTH_TYPE: CUSTOM
      RTL_CONFIG_PATH: /data/RTL.conf
      RTL_PASS: lightningcn
    ports:
        - "3000:3000"
    volumes:
        - ./rtldata:/data
        - ./lnd_data:/root/.lnd
        - ./bitcoin_data:/root/.bitcoin
    depends_on:
        - lnd_bitcoin
